//! `nexapipe status`: the management surface, from the command line.
//!
//! A client of the same `GET /v1/*` endpoints `nexapipe status` is the only
//! user of, which is the point: there is one thing that decides what the state
//! of an instance is — the running server — and this reads it rather than
//! reopening the config and guessing which parts of it have been reloaded since
//! startup. Anything read from the config file instead would be a second
//! answer, and the two would disagree after the first reload.
//!
//! # Why it reads the token off disk
//!
//! The token is generated by the server on first start, so the only place it
//! can be found is the file the server wrote. This command never creates one:
//! a `status` run is not a start, and a token minted by it would be a token the
//! server does not know about.
use crate::admin::token;
use crate::config::ProxyConfig;
use bytes::Bytes;
use http_body_util::{BodyExt, Full};
use hyper_util::client::legacy::Client;
use hyper_util::client::legacy::connect::HttpConnector;
use hyper_util::rt::TokioExecutor;
use serde_json::Value;
use std::net::SocketAddr;

/// One `GET /v1/*` call and its parsed body.
///
/// No status field because only a 200 ever gets this far: [`get`] turns
/// anything else into an error, so there is no `Answer` whose status is not
/// 200 and nothing to decide later.
struct Answer {
    name: &'static str,
    body: Value,
}

/// Asks a running instance what it is doing, and prints it.
///
/// `json` picks the whole answer as one document rather than the grouped
/// reading: the first is for a terminal, the second for anything that has to
/// parse it.
pub async fn status(config_path: &str, json: bool) -> anyhow::Result<()> {
    let config = ProxyConfig::from_file(config_path)?;
    let admin = config
        .admin
        .as_ref()
        .and_then(|admin| admin.listen_addr.as_ref());
    let Some(listen_addr) = admin else {
        anyhow::bail!(
            "{config_path} has no [admin] listen_addr, so this instance is not answering \
             questions about itself: add an [admin] section with a loopback address and restart"
        );
    };

    // Parsed rather than pasted into a URL: `SocketAddr`'s own Display is what
    // brackets an IPv6 address, and a wrong spelling of the host is an error
    // here rather than a request to somewhere else.
    let bound: SocketAddr = listen_addr
        .parse()
        .map_err(|_| anyhow::anyhow!("[admin] listen_addr is not an address: {listen_addr}"))?;
    let base = format!("http://{bound}");

    let token = token::load_existing(config_path).ok_or_else(|| {
        anyhow::anyhow!(
            "no admin token at {}; it is written when the server first starts with an [admin] \
             listener, so start the server once before asking it for its status",
            token::token_file_path(config_path)
        )
    })?;

    let client = http_client();
    let mut answers = Vec::new();
    // Every one, and all of them before anything is printed: a run that prints
    // three sections and then fails is a run whose output gets read as complete.
    for name in ["status", "routes", "clients", "connections", "health"] {
        answers.push(get(&client, &base, name, &token).await?);
    }

    if json {
        let mut document = serde_json::Map::new();
        for answer in &answers {
            document.insert((*answer.name).to_string(), answer.body.clone());
        }
        println!(
            "{}",
            serde_json::to_string_pretty(&Value::Object(document))?
        );
    } else {
        for answer in &answers {
            print_section(answer);
        }
    }

    Ok(())
}

/// One endpoint, as JSON.
async fn get(
    client: &Client<HttpConnector, Full<Bytes>>,
    base: &str,
    name: &'static str,
    token: &str,
) -> anyhow::Result<Answer> {
    let url = format!("{base}/v1/{name}");
    let request = hyper::Request::builder()
        .method("GET")
        .uri(&url)
        .header(hyper::header::AUTHORIZATION, format!("Bearer {token}"))
        .body(Full::new(Bytes::new()))?;

    let response = client
        .request(request)
        .await
        .map_err(|e| anyhow::anyhow!("cannot reach {url}: {e}"))?;
    let status = response.status().as_u16();
    let body = response
        .into_body()
        .collect()
        .await
        .map_err(|e| anyhow::anyhow!("cannot read the answer from {url}: {e}"))?
        .to_bytes();

    // Told as the server said it, not translated: a 401 and a 503 mean
    // different things and the body is written to say which.
    if status != 200 {
        let said = String::from_utf8_lossy(&body);
        anyhow::bail!("{url} answered {status}: {}", said.trim());
    }

    let body = serde_json::from_slice(&body)
        .map_err(|e| anyhow::anyhow!("{url} did not answer with JSON ({e})"))?;
    Ok(Answer { name, body })
}

/// A client for one loopback call.
///
/// Built here rather than reusing the proxy's own client because that one is
/// tuned for forwarding to backends — a large idle pool, keepalive, lenient
/// header parsing — none of which means anything for a single request to
/// ourselves.
fn http_client() -> Client<HttpConnector, Full<Bytes>> {
    Client::builder(TokioExecutor::new()).build_http()
}

/// One endpoint's answer, as a group of lines.
fn print_section(answer: &Answer) {
    match answer.name {
        "status" => print_status(&answer.body),
        "routes" => print_routes(&answer.body),
        "clients" => print_clients(&answer.body),
        "connections" => print_connections(&answer.body),
        "health" => print_health(&answer.body),
        _ => println!("{}: {}", answer.name, answer.body),
    }
}

fn print_status(body: &Value) {
    println!("Instance");
    println!("  version:         {}", text(body, "version"));
    println!("  uptime:          {}s", text(body, "uptime_seconds"));

    let connections = &body["connections"];
    println!(
        "  connections:     {} open ({} direct, {} relayed, {} unknown), {} since start",
        num(connections, "active"),
        num(connections, "direct"),
        num(connections, "relayed"),
        num(connections, "unknown"),
        num(connections, "total"),
    );
    println!(
        "  backends:        {} up, {} down",
        num(&body["backends"], "up"),
        num(&body["backends"], "down"),
    );
    println!("  routes:          {}", num(body, "routes"));
    println!("  peers:           {}", num(body, "peers"));
    println!("  in flight:       {}", num(body, "in_flight"));

    // Only the classes that are not zero: six lines of which five say "0" is a
    // table nobody reads, and the point of the answer is what happened.
    let requests: Vec<String> = body["requests"]
        .as_array()
        .into_iter()
        .flatten()
        .filter(|entry| entry["count"].as_u64().unwrap_or(0) > 0)
        .map(|entry| format!("{}: {}", text(entry, "class"), num(entry, "count")))
        .collect();
    println!(
        "  requests:        {}",
        if requests.is_empty() {
            "none".to_string()
        } else {
            requests.join(", ")
        }
    );

    let flows: Vec<String> = body["l4_flows"]
        .as_array()
        .into_iter()
        .flatten()
        .filter(|entry| entry["count"].as_u64().unwrap_or(0) > 0)
        .map(|entry| {
            format!(
                "{} {}: {}",
                text(entry, "proto"),
                text(entry, "class"),
                num(entry, "count")
            )
        })
        .collect();
    if !flows.is_empty() {
        println!("  l4 flows:        {}", flows.join(", "));
    }

    println!(
        "  2FA:             {} ({} clients)",
        if body["auth"]["enabled"].as_bool().unwrap_or(false) {
            "on"
        } else {
            "off"
        },
        num(&body["auth"], "clients"),
    );
    println!();
}

fn print_routes(body: &Value) {
    println!("Routes");
    let routes = body["routes"].as_array();
    let Some(routes) = routes.filter(|routes| !routes.is_empty()) else {
        println!("  none");
        println!();
        return;
    };

    for route in routes {
        let modes: Vec<&str> = route["modes"]
            .as_array()
            .into_iter()
            .flatten()
            .filter_map(|mode| mode.as_str())
            .collect();
        let checked = route["health_checked"].as_bool().unwrap_or(false);
        println!(
            "  {}  [{}]{}",
            text(route, "host_pattern"),
            modes.join(", "),
            if checked { "" } else { "  (not probed)" },
        );
        for backend in route["backends"].as_array().into_iter().flatten() {
            println!(
                "      {} {}",
                if backend["healthy"].as_bool().unwrap_or(false) {
                    "up  "
                } else {
                    "DOWN"
                },
                text(backend, "url"),
            );
        }
    }
    println!();
}

fn print_clients(body: &Value) {
    println!("Clients");
    if !body["enabled"].as_bool().unwrap_or(false) {
        println!("  2FA is off, so no client is authenticated");
        println!();
        return;
    }

    let clients = body["clients"].as_array();
    let Some(clients) = clients.filter(|clients| !clients.is_empty()) else {
        println!("  none configured");
        println!();
        return;
    };

    for client in clients {
        println!(
            "  {}  secret: {}  hosts: {}",
            text(client, "id"),
            if client["has_secret"].as_bool().unwrap_or(false) {
                "enrolled"
            } else {
                "MISSING"
            },
            match client["allow_hosts"].as_array() {
                Some(hosts) if !hosts.is_empty() => hosts
                    .iter()
                    .filter_map(|host| host.as_str())
                    .collect::<Vec<_>>()
                    .join(", "),
                // `null` is every route and `[]` is none, and the two read the
                // same if this is shortened to "no restriction".
                Some(_) => "none, every host is denied".to_string(),
                None => "every route".to_string(),
            },
        );
        if client["locked_until"].is_number() {
            println!("      locked out");
        }
    }
    println!();
}

fn print_connections(body: &Value) {
    println!("Connections");
    let peers = body["peers"].as_array();
    let Some(peers) = peers.filter(|peers| !peers.is_empty()) else {
        println!("  nobody is connected");
        println!();
        return;
    };

    for peer in peers {
        println!(
            "  {}  {}  for {}s",
            text(peer, "endpoint_id"),
            text(peer, "path"),
            num(peer, "connected_for_seconds"),
        );
    }
    println!();
}

fn print_health(body: &Value) {
    println!("Backend health");
    println!(
        "  {} up, {} down",
        num(body, "backends_up"),
        num(body, "backends_down"),
    );
    for route in body["routes"].as_array().into_iter().flatten() {
        println!("  {}", text(route, "host_pattern"));
        for backend in route["backends"].as_array().into_iter().flatten() {
            println!(
                "      {} {}",
                if backend["healthy"].as_bool().unwrap_or(false) {
                    "up  "
                } else {
                    "DOWN"
                },
                text(backend, "url"),
            );
        }
    }
    println!();
}

/// A field as a string, or a dash: the shape is the server's to change, and a
/// missing key is not a reason for this command to fail.
fn text(value: &Value, key: &str) -> String {
    match &value[key] {
        Value::String(s) => s.clone(),
        Value::Number(n) => n.to_string(),
        Value::Bool(b) => b.to_string(),
        _ => "-".to_string(),
    }
}

/// A field as a number, or zero, for the same reason as [`text`].
fn num(value: &Value, key: &str) -> u64 {
    value[key].as_u64().unwrap_or(0)
}
